### ISSUE TITLE
Fixes after feedback

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#189]
- [x] 1. Вместо кнопки Цель шага - сделать 'О шаге' и туда занести  весь текст интро этого шага #198
- [x] 2. В личных и командных заметках - ведёрко сделать  вправо и вверх, текст заметки убрать из списка #215
- [x] 3. Сделать компонент Инфо и туда 2 кнопки - ВВедение в главу и ВВедение в книгу - во все шаги , где есть Библия. #122 
- [x] 4. Слева в драфте  - удалить все чекбоксы, справа - логику  исправить- добавить карандашик #200 
- [x] 5. Не допускать отправлять пустые стихи при переходе на другой шаг #200 
- [x] 6. В TQ cделать ответ другим цветом - как в кнопке btn-cyan #198
- [x] 7. Отображать все стихи на 7 шаге, а вот редактировать можно только свой диапазон #199 
- [x] 8. На 8 шаге  - редактирует только модератор - сделать такой компонент/ или параметр для текущего #164
