### ISSUE TITLE
New fixes for feadback from Demo

### ISSUE THREAD

**Issue by Valyukhov** [texttree/v-cana#208]
- [x] По клику на корзину - модалка - точно удалить? - Командные и личные заметки #215 
- [x]  Кнопку удалить все заметки - Личные заметки #215 
- [x]  Модалка :О шаге: - контент прижать влево, заголовок оставить по-центру #213 
- [x]  Кнопка в БлайндДрафт с карандашом - зафиксировать размер, чтобы она не расползалась #213
- [x]  Исправить CTRL+Z #213
- [x]  убрать выделение серым в драфте текстареа справа и сделать фокус, слева сделать серым уже переведенный стих #213
- [x]  Жирный тёмно-синий Или синим все остальные, твои номера жирным черным #213
